rofi-sink + rofi-script fixes

diff --git a/.local/bin/rofi-editconfig b/.local/bin/rofi-editconfig
--- a/.local/bin/rofi-editconfig
+++ b/.local/bin/rofi-editconfig
@@ -1,10 +1,14 @@
 #!/usr/bin/env bash
 
-if [ "$#" -lt 1 ]; then
-    echo -en "\x00prompt\x1fEdit file\n"
-    bookmarks file
-else
-    [ -f "$*" ] && coproc {
-        sensible-terminal -e sensible-editor "$"
-    } >/dev/null 2>&1
-fi
+case "$ROFI_RETV" in
+    0) # Initial call of script
+        echo -en "\x00prompt\x1fEdit file\n"
+        bookmarks file
+        ;;
+    1) # Selected an entry
+        [ -f "$*" ] && coproc {
+            sensible-terminal -e sensible-editor "$*"
+        } >/dev/null 2>&1
+        ;;
+    *)  echo "error: need to run from rofi" ; exit 1 ;;
+esac
diff --git a/.local/bin/rofi-emoji b/.local/bin/rofi-emoji
--- a/.local/bin/rofi-emoji
+++ b/.local/bin/rofi-emoji
@@ -14,19 +14,23 @@ while [ ! -s "$file" ]; do
             }' > "$file"
         unset dl
     else
-        notify-send "Rofiunicode" "Error downloading emoji file from unicode.org"
+        notify-send "rofi-emoji" "Error downloading emoji file from unicode.org"
         exit 1
     fi
 done
 
-if [ "$#" -lt 1 ]; then
-    echo -en "\x00prompt\x1fSelect emoji\n"
-    cat "$file"
-else
-    chosen="${1%%[[:space:]]*}"
-    [ -z "$chosen" ] && exit 0
-    coproc {
-        printf "%s" "$chosen" | xclip -selection clipboard
-        notify-send "Rofiunicode" "'$chosen' copied to clipboard."
-    } >/dev/null 2>&1
-fi
+case "$ROFI_RETV" in
+    0) # Initial call of script
+        echo -en "\x00prompt\x1fSelect emoji\n"
+        cat "$file"
+        ;;
+    1) # Selected an entry
+        chosen="${1%%[[:space:]]*}"
+        [ -z "$chosen" ] && exit 0
+        coproc {
+            printf "%s" "$chosen" | xclip -selection clipboard
+            notify-send "rofi-emoji" "'$chosen' copied to clipboard."
+        } >/dev/null 2>&1
+        ;;
+    *)  echo "error: need to run from rofi" ; exit 1 ;;
+esac
diff --git a/.local/bin/rofi-exit b/.local/bin/rofi-exit
--- a/.local/bin/rofi-exit
+++ b/.local/bin/rofi-exit
@@ -1,15 +1,22 @@
 #!/usr/bin/env bash
 
-case "$*" in
-    "Lock screen") coproc { light-locker-command --lock; } ;;
-    "Exit/logout") coproc { awesome-client 'awesome.quit()' >/dev/null 2>&1; } ;;
-    "Suspend") coproc { systemctl suspend; } ;;
-    "Reboot") coproc { systemctl reboot; } ;;
-    "Shutdown") coproc { systemctl poweroff -i; } ;;
-    *)  echo -en "\x00prompt\x1fSystem exit\n"
+case "$ROFI_RETV" in
+    0) # Initial call of script
+        echo -en "\x00prompt\x1fSystem exit\n"
         echo "Lock screen"
         echo "Exit/logout"
         echo "Suspend"
         echo "Reboot"
         echo "Shutdown"
+        ;;
+    1) # Selected an entry
+        case "$*" in
+            "Lock screen") coproc { light-locker-command --lock; } ;;
+            "Exit/logout") coproc { awesome-client 'awesome.quit()' >/dev/null 2>&1; } ;;
+            "Suspend") coproc { systemctl suspend; } ;;
+            "Reboot") coproc { systemctl reboot; } ;;
+            "Shutdown") coproc { systemctl poweroff -i; } ;;
+        esac
+        ;;
+    *)  echo "error: need to run from rofi" ; exit 1 ;;
 esac
diff --git a/.local/bin/rofi-man b/.local/bin/rofi-man
--- a/.local/bin/rofi-man
+++ b/.local/bin/rofi-man
@@ -1,13 +1,16 @@
 #!/usr/bin/env bash
 
-if [ "$#" -lt 1 ]; then
-    echo -en "\x00prompt\x1fSelect man page\n"
-    man -k . | awk '{ print $1 }'
-else
-    tempfile=$(mktemp)
-    man -Tpdf "$*" > "$tempfile"
-    coproc {
-        zathura "$tempfile"
-        rm -f "$tempfile"
-    } >/dev/null 2>&1
-fi
+case "$ROFI_RETV" in
+    0) # Initial call of script
+        echo -en "\x00prompt\x1fSelect man page\n"
+        man -k . | awk '{ print $1 }'
+        ;;
+    1) # Selected an entry
+        tempfile=$(mktemp)
+        man -Tpdf "$*" > "$tempfile"
+        coproc {
+            zathura "$tempfile"
+        } >/dev/null 2>&1
+        ;;
+    *)  echo "error: need to run from rofi" ; exit 1 ;;
+esac
